version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - python_server
    networks:
      - webnet

  python_server:
    build: ./python_server
    ports:
      - "8000:8000"
    networks:
      - webnet

  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=emilia.trybala
      - POSTGRES_PASSWORD=emilka2024
      - POSTGRES_DB=baza_lab2
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres_init:/docker-entrypoint-initdb.d/
    networks:
      - webnet

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=emilia.trybala@student.pk.edu.pl
      - PGADMIN_DEFAULT_PASSWORD=emilka2024
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - webnet

networks:
  webnet: